# Building a deep neural network from scratch for handwritten digit recognition

In [3]:
import numpy as np
import pandas as pd

## First, let's define all our math functions

1) One Hot encoder

In [16]:
def one_hot(labels):
    y_true = np.zeros([10, len(labels)])
    for i in range(len(labels)):
        y_true[labels[i], i] = 1
    return y_true

print(one_hot([3,0,2,7]))

[[0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


2) ReLU activation and derivative

In [ ]:
def relu(z):
    return (np.maximum(0, z))


def relu_derivative(z):
    return (z > 0).astype(float) # Converts True to 1. and False to 0. which are ReLu derivatives

3. Softmax activation

In [ ]:
def softmax(z):
    
    # subtract max of z for numerical stability and prevent overflow. This does not change the output as the constant cancels in the numerator and denominator.

    exp_z = np.exp(z - np.max(z, axis=0, keepdims=True)) 
    return exp_z / np.sum(exp_z, axis=0, keepdims=True)   # sum over columns for normalization

4. Forward Pass for a two layer network

In [ ]:
def forward_pass(x0, w1, b1, w2, b2):
    z1 = w1.T @ x0+b1
    x1 = relu(z1)
    z2 = w2.T @ x1+b2
    x2 = softmax(z2)
    return z1, x1, x2